export const skills = [
    "React",
    "Javascript",
    "Next JS",
    "Express",
    "Css",
    "HTML",
    "TypeScript",
    "Tailwind Css",
    "Flutter",
    "Dart",
    "Node JS",
    "Redis",
    "Material-UI",
    "Android",
    "Git",
    "Postman",
    "GraphQL",
    "MongoDB",
    "SQL",
    "Svelte",
    "React Native",
    "SEO",
    "Prisma",
    "Redux",
    "Zod",
    "Zustand"
]